### ISSUE TITLE
Crash at the summon selection page v1.2.1

### ISSUE THREAD

**Issue by Kyanberu** [Masuzu/SarasaBot#14]
After update to v1.2.1 bot crash at the summon selection page

https://imgur.com/a/OZQ7Z

**Comment by Masuzu** [comment]
Hi,

Please provide a full screenshot showing the last lines in the log of the console (some debug messages were adde there). I can't understand what the issue is otherwise.

**Comment by Kyanberu** [comment]
here is a screenshot https://imgur.com/a/9s5yb

**Comment by thenastyworm** [comment]
Can confirm - I have the same crashes. They seem to occur at random and with no noticeable pattern. At first I thought it was related to the amount of soul berries consumed, but that seems to be not the case. 

I have since taken out the white rabbit from the summon list and instead started using more common on element summons and did not have a crash since. Maybe it's related to that. Will report back if I do crash with this new setup.

**Comment by Masuzu** [comment]
Thank you for the additional info, I believe I pinpointed the issue. v1.2.2 to be released in a few minutes.

**Comment by Masuzu** [comment]
v1.2.2 is out https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-2

**Comment by LordShade** [comment]
that fixed it. Thanks @Masuzu

**Comment by Masuzu** [comment]
That's great news! Thank you for the feedback, closing this issue then.
