### ISSUE TITLE
Serial number matches but can not boot.

### ISSUE THREAD

**Issue by MacchoHunter** [Masuzu/SarasaBot#146]
The serial number matches, but the bot does not work.
![205923eaede10811233bfaf7995d76be](https://user-images.githubusercontent.com/38382971/38770745-a306bdb2-4052-11e8-89b6-69fd9d49b591.jpg)

**Comment by Masuzu** [comment]
Hello,
It can sometimes happen in certain cases.
Instead of using the serial number generator, check the `serial_number.txt` file created in the same folder as `SarasaBot.exe` and copy and paste the contents of that file instead. It should be different than the one generated by the serial number generator.
Make sure to redownload a clean copy of your key.txt file afterwards if you still have issues.
