### ISSUE TITLE
Unable to cast summons

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/SarasaBot#165]
After updating to version 1.9.2 the bot seems to ignore the line to cast summons

These seems to only happen with the new  option Enableearlyturnstart with viramate set to true

**Comment by Masuzu** [comment]
Hello,
Increasing the value of `MaxNumRetries` should help with this issue.
I will look into it, but this is one of the reasons why the feature `Enableearlyturnstart` is disabled by default.

**Comment by Masuzu** [comment]
Actually there is a slight bug with the way Sarasa and Zooey bots handle the summon availability. I did not look into how to solve it for now due to a severe lack of time but on the bright side, once this is implemented, using summons twice in a turn (Lyria and Arcarum summons for instance) will become possible.

**Comment by Masuzu** [comment]
This is now addressed in v1.9.4.
