### ISSUE TITLE
Bot Alarm still not working

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/SarasaBot#184]
As described in a previous issue, the bot alarm only sounds for 1 second, then proceeds to shut itself.
#177 
Current Version of Sarasa bot used is 1.9.9, so the issue doesnt seem to be fixed

Currently using Chromium Version: 67.0.3367.0 (64-bit)

Bot does not calibrate with Chrome Version 67.0.3396.79
Captcha notification settings are unchanged
NumNotifications set to 9999.
@Masuzu 

This happens whether or not EnableEarlyTurnStartWithViramate is set to true or false

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this. I am afraid I can't tell for now what the issue is then, but I will add logging messages in the next release to see what really happens.
As an alternative, using a very long sound alert instead of the default one provided.
The calibration works fine with Version 67.0.3396.79 as I am using it right now.

**Comment by fdxcfdxc** [comment]
It doesn't work for me too, and I was banned for several hours because I didn't see it. Really need to be fixed immediately.

**Comment by esseral** [comment]
Problem here is that the bot always crashes a couple of seconds after the captcha pops up, so it doesn't matter how long the alert sound is, because if the bot has crashed, the alert stops playing.

Please fix ASAP - in the current state, Sarasa is NOT safe to use because you can't go afk while it's running.

**Comment by UminekoScarlet** [comment]
I got the same problem. As was already said, the sound effect only plays for like a second, then the bot crashes. I can't use as much as I'd like too, because it's easy to not hear the sound this way.

**Comment by CorrinKrow** [comment]
@Masuzu can we get an update on these bug, Its been almost a month since this issue has occurred

**Comment by Masuzu** [comment]
A mitigation is now provided in v1.9.10
