### ISSUE TITLE
Sarasa crashing

### ISSUE THREAD

**Issue by lamewood** [Masuzu/SarasaBot#216]
The bot is crashing for me after a different amount of time. I couldn't see any failure lines but I've set it up for Metatron raids "RaidsToTrack=Lvl 120 Metatron, Lv120 メタトロン" and it seemingly works perfectly fine as intended.
I've enabled Viramate shortcuts and in the .ini with the EnableEarlyTurnStartWithViramate=true
I noticed that the bot crashes outside of the raid, where it has executed it's lua commands.
I hope you can help out with this information

**Comment by zappky** [comment]
You didnt provide enough information to narrow down where and why the bot has crashed for you. 
Personally, the bot didnt crash at any point in time with the latest version 3. You may want to consider updating your version if you are using older ones.

One common point of failure is to check whether your lua script has any faulty syntax. This should be easy to detect as the program will tell you which line has a fault. Otherwise maybe you have accidentally put a very small amount of time on the "TimeLimitInSeconds" variable which cause the program to close itself far too early. 

If you still have problem,it maybe a viramate and sarasa bot interaction problem which i would't know since i do not use viramate

I hope i at least help you a little.

Perhaps you can elaborate on this point: "the bot crashes outside of the raid",so that people can better help you.

**Comment by lamewood** [comment]
While using the bot the past few days, i noticed that it just crashes without any error in the console.
It always happenes when it is searching for raids - not during raids.
I'm using the sarasa-bot-v2.0.0 which is the most recent one.
I could try to use it without viramate, but previously it didnt had any issues either.
Other than that, i havent changed much in terms of the time intervals and stuff. I only changed the name of the raids to track

**Comment by lamewood** [comment]
These are the things i changed:
9.	RaidsToTrack=Lvl 120 Metatron, Lv120 メタトロン
10.	#Lvl 120 Metatron, Lv120 メタトロン
11.	#Lv90 アグニス, Lvl 90 Agni
12.	#Lv90 ゼピュロス, Lvl 90 Zephyrus
13.	#Lv90 ティターン, Lvl 90 Titan
14.	#Lv90 ネプチューン, Lvl 90 Neptune
16.	MaxNumPlayersInRaid=10
18.	MinimumRemainingBossHpPercentage=45
20.	MaximumRemainingBossHpPercentage=100
31.	MaxNumSoulBerries=800
35.	MaxNumSoulBalms=200
49.	UseViramate=true
51.	OngoingRaidsCheckFrequencyInSeconds=20
80.	PreferredSummons=Bahamut, Celeste Omega, Kaguya,White Rabbit
86.	RerollSummonWhenNoPreferredSummonWasFound=true
98.	LuaScript=Scripts/dark.lua
105.	EnableEarlyTurnStartWithViramate=true

**Comment by lamewood** [comment]
I disabled "EnableEarlyTurnStartWithViramate=true" and it works just fine now
