### ISSUE TITLE
Question: What happens when a captcha is found and ignored for hours?

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/SarasaBot#224]
So im asking this because I have no idea if i got a captcha or not. I left the bot on for 3 hours and seems to have stopped/crashed midway.  So does captcha stay indefinitely in the screen or does it disappear ? I want to know if it stopped due to captcha or any other reason. 

Thanks.

**Comment by xerance** [comment]
you get temp banned.
source happen once for me and twice for a friend.

**Comment by breinjhel** [comment]
I see. Thanks for the info

**Comment by meteoshower** [comment]
@xerance  I've got temp banned second time .do you think may i have any chance to  unban

**Comment by xerance** [comment]
@meteoshower afaik 3rd ban is final, never heard about anyone getting unbanned

**Comment by ErogeSeiyuu** [comment]
Pretty sure the bans are 24 hours, 3 days, 1 week, then 1 month, and then permaban.

I reached the 1 week ban last year due to being dumb with handling casinobot and a guildmate reached 1 month.

There's a new update yesterday though and 97 was permabanned. Anybody knows if zoibot and sarasabot are detected yet or not?

**Comment by Masuzu** [comment]
The last versions of Zooey Bot and Sarasa Bot do detect properly the new verification checks.
