### ISSUE TITLE
New to the Twitter dev thing

### ISSUE THREAD

**Issue by Santheron** [Masuzu/SarasaBot#243]
What am I supposed to fill in to these text boxes?

![image](https://user-images.githubusercontent.com/40581698/52229667-b59f2780-2872-11e9-8708-abe45b397c6d.png)

It's on the process of making a twitter app for the dev account.

**Comment by Masuzu** [comment]
Hello,
It looks like things changed since the last update.
Any personal website (preferably one that you own) would be the best choice. In some cases a fictive website URL would work too.
In any case you will have to fill in the intended usage for your Twitter application. Creativity is fine, but try to avoid things like "collecting user data" and privacy related matters.
You just want to have your Twitter Dev account created to obtain a twitter token for Sarasa bot.
