### ISSUE TITLE
Issue joining raids quickly

### ISSUE THREAD

**Issue by arcswin18** [Masuzu/SarasaBot#275]
Is there a way to make raid joining as quick as possible? The process of joining the raid is fast but selecting summons take a while which matters for stuff like Ultimate bahamut or tiamat malice. I have the preferred summon set to blank so that it'll select the first slot but theres still a delay even after changing the mouse delay settings so raids always fill up before I have time to join especially if they are low hp.

**Comment by Masuzu** [comment]
Hi,
The mouse is usually already on top of summon selection menu so movements should be minimal (selecting the summon which is directly under the mouse would be an option for future releases).
Make sure to use the `QuickRaidJoining` mode and if ping is an issue, in order to compete against other automated raid joiners, you _have to_ use a machine directly located in Tokyo https://www.youtube.com/watch?v=Bql08hzhcZQ
