### ISSUE TITLE
Sarasa Bot stucks at normal raid page

### ISSUE THREAD

**Issue by mumu09** [Masuzu/SarasaBot#50]
Zooey bot runs successfully on my pc but Sarasa Bot stucks at the normal raid page and keeps refreshing while saying ''Back trying to join a raid.". I set up the bot according to the guide. (I have all the twitter app stuff.)
![sarasa stuck](https://user-images.githubusercontent.com/35623117/35181321-b5537c02-fdfa-11e7-8fc3-39de25fcc962.png)

**Comment by Masuzu** [comment]
Hello,
It is not a bug. Set `DisplayRaids=true` to see the list of raids captured and make sure to set `RaidsToTrack` to a correct value (exact case matching!, for instance `RaidsToTrack=Lvl 100 Yggdrasil Omega,Lv100 ユグドラシル・マグナ`). If no raids were found then it will loop like shown in your picture, which is the expected behaviour.
If you try and join very infrequent raids (Bahamut HL, Qijin and the likes) it will also be the case.
