### ISSUE TITLE
1.6.2 Not Working

### ISSUE THREAD

**Issue by optiblast** [Masuzu/SarasaBot#65]
I've been using your bots for nearly 3 months now and this is the 1st time that this happened on sarasa. License cost $5 a week so please fix asap.

https://streamable.com/sfp08

**Comment by DarkenShade** [comment]
reposting this here since the issue is 1.6.2 and the other thread was for 1.6.1
---------------------------------------------------------------------------------------------------------------
I also have this problem.

i got the product yesterday and tried 1.6.1 but it would not say or do anything past "good to go" and did not list any raids.

i then went to 1.5.1 and it worked perfectly.

today when it was updated to 1.6.2, 1.5.1 stoped working so i tried to use 1.6.2 and it has the same problem as 1.6.1

**Comment by Miragith** [comment]
Just bought the week license and this is not working. Will there be a compensation for the lost time?

**Comment by MillionRice** [comment]
I saw an upgrade this morning and expected to work as usual. But just the same as 1.6.1. It just happened again. "Good to go" and nothing pops up. Normally, there should be twitter information displayed. I have already used Zooey bot for half a year. Usually, I will try to fix it by trying different settings, but this time I just have no idea. So please fix this asap, as I can not use it since the first day I purchased this license.

**Comment by ladysour** [comment]
I have the same problem, kinda regret getting the licence without checking the issues, oops. I don't really care about compensation but I was wondering if the problem is acknowledged or if there's an ETA for the fix ^.^

**Comment by GBFThrowaway** [comment]
Same issue, just bought the license but can't use it.

**Comment by CorrinKrow** [comment]
Also have the same problem, would just like an ETA on the fix soon

**Comment by Masuzu** [comment]
Hello,

I will provide a fix for Sarasa Bot later in the day and provide a compensation as well for affected users.
I apologize for the inconvenience.

https://twitter.com/GBFPokerBot/status/960805535800012800

**Comment by CorrinKrow** [comment]
Thank you for the quick response.

**Comment by Masuzu** [comment]
ETA for the fix: about 13 hours from now - February 7, 8 AM JST

After the issue is addressed, if your Sarasa Bot licence expired in the past 4 days, please kindly mail me your serial number at `sarasa-bot-support@azuriteworlds.com` with for subject `SarasaBot Issue 65` to redeem the compensation. Thank you for your cooperation.

Thank you for your understanding and cooperation
--

**Comment by Masuzu** [comment]
Sarasa is now back with version 1.6.3.
